# Strong signals that a role is intended for students / early-career candidates.
STUDENT_KEYWORDS = [
    "working student",
    "student position",
    "student role",
    "student software",
    "student developer",
    "student engineer",
    "student",
    "internship",
    "intern",
    "co-op",
    "coop",
    "new college grad",
    "new grad",
    "graduate software",
    "graduate engineer",
    "entry level",
    "entry-level",
    "junior",
    "part time",
    "part-time",
    "undergraduate",
]


# Strong technical role words. A title containing one of these is usually
# relevant even if it does not explicitly say "student".
TECH_TITLE_KEYWORDS = [
    "software",
    "backend",
    "back-end",
    "frontend",
    "front-end",
    "full stack",
    "full-stack",
    "developer",
    "validation",
    "verification",
    "v&v",
    "embedded",
    "firmware",
    "system software",
    "systems software",
    "devops",
    "site reliability",
    "sre",
    "qa",
    "quality assurance",
    "test automation",
    "automation engineer",
    "sdet",
    "test engineer",
    "security engineer",
    "cyber security",
    "cybersecurity",
    "application security",
    "product security",
    "cloud engineer",
    "platform engineer",
    "infrastructure engineer",
    "data engineer",
    "machine learning",
    "ml engineer",
    "computer vision",
    "algorithm",
    "algorithms",
    "fpga",
    "rtl",
    "design verification",
    "post silicon",
    "post-silicon",
    "pre silicon",
    "pre-silicon",
    "silicon validation",
    "hardware validation",
]


# Weaker title words: useful, but too broad to accept on their own.
WEAK_TECH_TITLE_KEYWORDS = [
    "engineer",
    "engineering",
    "r&d",
    "research",
    "technical",
    "technology",
]


# Technical context words. These let us keep broad titles such as
# "R&D Intern" or "Engineering Student" when the description is clearly CS/tech.
TECH_CONTEXT_KEYWORDS = [
    "computer science",
    "software engineering",
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    " c ",
    "linux",
    "unix",
    "git",
    "docker",
    "kubernetes",
    "api",
    "rest",
    "backend",
    "frontend",
    "full stack",
    "full-stack",
    "embedded",
    "firmware",
    "kernel",
    "driver",
    "drivers",
    "operating system",
    "networking",
    "tcp",
    "ip",
    "validation",
    "verification",
    "testing",
    "automation",
    "systemverilog",
    "verilog",
    "fpga",
    "rtl",
    "silicon",
    "chip",
    "semiconductor",
    "debug",
    "debugging",
    "security",
    "cyber",
    "cloud",
    "devops",
    "database",
    "sql",
    "algorithms",
    "data structures",
    "machine learning",
    "computer vision",
]


# Senior roles are filtered out before scoring.
EXCLUDE_KEYWORDS = [
    "senior",
    "sr.",
    "sr ",
    "lead",
    "team lead",
    "manager",
    "principal",
    "staff",
    "director",
    "head of",
    "architect",
    "vp ",
    "vice president",
]


ISRAEL_LOCATIONS = [
    "israel",
    "tel aviv",
    "tel-aviv",
    "haifa",
    "yokneam",
    "herzliya",
    "raanana",
    "ra'anana",
    "kfar saba",
    "petah tikva",
    "petah-tikva",
    "netanya",
    "caesarea",
    "rehovot",
    "ness ziona",
    "rishon lezion",
    "rishon le-zion",
    "jerusalem",
    "beer sheva",
    "be'er sheva",
    "migdal ha'emek",
    "migdal haemek",
    "hadera",
    "yavne",
    "glil yam",
]
