# Signals that the role is intended for a current student/intern or true entry-level candidate.
# Junior / new-grad roles remain excluded.
STUDENT_KEYWORDS = [
    "working student",
    "student position",
    "student role",
    "student software",
    "student developer",
    "student engineer",
    "software student",
    "engineering student",
    "student",
    "internship",
    "intern",
    "co-op",
    "coop",
    "undergraduate",
    "entry level",
    "entry-level",
]


# Strong technical role words.
TECH_TITLE_KEYWORDS = [
    "software",
    "backend",
    "back-end",
    "frontend",
    "front-end",
    "full stack",
    "full-stack",
    "developer",
    "validation",
    "verification",
    "v&v",
    "embedded",
    "firmware",
    "system software",
    "systems software",
    "devops",
    "site reliability",
    "sre",
    "qa",
    "quality assurance",
    "test automation",
    "automation engineer",
    "sdet",
    "test engineer",
    "security engineer",
    "cyber security",
    "cybersecurity",
    "application security",
    "product security",
    "cloud engineer",
    "platform engineer",
    "infrastructure engineer",
    "data engineer",
    "machine learning",
    "ml engineer",
    "computer vision",
    "algorithm",
    "algorithms",
    "fpga",
    "rtl",
    "design verification",
    "post silicon",
    "post-silicon",
    "pre silicon",
    "pre-silicon",
    "silicon validation",
    "hardware validation",
]


# Weaker technical title words. These require technical context too.
WEAK_TECH_TITLE_KEYWORDS = [
    "engineer",
    "engineering",
    "r&d",
    "research",
    "technical",
    "technology",
]


# Technical context words used to verify broad student/intern titles.
TECH_CONTEXT_KEYWORDS = [
    "computer science",
    "software engineering",
    "computer engineering",
    "electrical engineering",
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    " c ",
    "linux",
    "unix",
    "git",
    "docker",
    "kubernetes",
    "api",
    "rest",
    "backend",
    "frontend",
    "full stack",
    "full-stack",
    "embedded",
    "firmware",
    "kernel",
    "driver",
    "drivers",
    "operating system",
    "networking",
    "tcp",
    "validation",
    "verification",
    "testing",
    "automation",
    "systemverilog",
    "verilog",
    "fpga",
    "rtl",
    "silicon",
    "chip",
    "semiconductor",
    "debug",
    "debugging",
    "security",
    "cyber",
    "cloud",
    "devops",
    "database",
    "sql",
    "algorithms",
    "data structures",
    "machine learning",
    "computer vision",
]


# Titles that are clearly outside the software / validation / engineering
# student roles this bot is intended to find.
NON_TECH_TITLE_KEYWORDS = [
    "accounting",
    "accountant",
    "finance",
    "financial",
    "bookkeeper",
    "marketing",
    "sales",
    "legal",
    "law ",
    "human resources",
    " hr ",
    "recruiter",
    "recruiting",
    "talent acquisition",
    "customer success",
    "business development",
    "business analyst",
    "product marketing",
    "procurement",
]


# Senior roles are filtered out before scoring.
EXCLUDE_KEYWORDS = [
    "senior",
    "sr.",
    "sr ",
    "lead",
    "team lead",
    "manager",
    "principal",
    "staff",
    "director",
    "head of",
    "architect",
    "vp ",
    "vice president",
]


ISRAEL_LOCATIONS = [
    "israel",
    "tel aviv",
    "tel-aviv",
    "haifa",
    "yokneam",
    "herzliya",
    "raanana",
    "ra'anana",
    "kfar saba",
    "petah tikva",
    "petah-tikva",
    "netanya",
    "caesarea",
    "rehovot",
    "ness ziona",
    "rishon lezion",
    "rishon le-zion",
    "jerusalem",
    "beer sheva",
    "be'er sheva",
    "migdal ha'emek",
    "migdal haemek",
    "hadera",
    "yavne",
    "glil yam",
    "ramat gan",
    "ramat-gan",
    "bnei brak",
    "bnei-brak",
    "holon",
    "or yehuda",
    "or-yehuda",
    "rosh haayin",
    "rosh ha'ayin",
    "kiryat gat",
    "modiin",
    "modi'in",
]
