TECH_KEYWORDS = [
    "software",
    "developer",
    "backend",
    "validation",
    "verification",
    "embedded",
    "student",
    "intern",
    "engineer",
    "junior",
]

EXCLUDE_KEYWORDS = [
    "senior",
    "lead",
    "manager",
    "principal",
    "staff",
    "director",
    "sr.",
]

ISRAEL_LOCATIONS = [
    "israel",
    "tel aviv",
    "tel-aviv",
    "haifa",
    "yokneam",
    "herzliya",
    "raanana",
    "ra'anana",
    "kfar saba",
    "petah tikva",
    "petah-tikva",
    "netanya",
    "caesarea",
    "rehovot",
    "ness ziona",
    "rishon lezion",
    "rishon le-zion",
    "jerusalem",
    "beer sheva",
    "be'er sheva",
    "migdal ha'emek",
    "migdal haemek",
    "hadera",
    "yavne",
    "glil yam",
]
